apps/application/urls.py
# -*- coding: utf-8 -*-

__author__ = u'teehamaral'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^$', 'apps.application.views.login', name='app_login'),

                       url(r'^importar-redes-de-protecao/$', 'apps.application.views.import_protectionnetworks', name='app_import_protectionnetworks'),

                       url(r'^esqueceu-a-senha/$', 'apps.application.views.forgotpassword', name='app_forgotpassword'),
                       url(r'^dashboard/$', 'apps.application.views.dashboard', name='app_dashboard'),

                       url(r'^usuarios/$', 'apps.application.views.users_list', name='app_userslist'),
                       url(r'^usuarios/adicionar/$', 'apps.application.views.users_add', name='app_usersadd'),
                       url(r'^usuarios/editar/(?P<id>[\w-]+)/$', 'apps.application.views.users_edit', name='app_usersedit'),
                       url(r'^usuarios/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.users_del', name='app_usersdel'),
                       url(r'^usuarios/alterar-senha/(?P<id>[\w-]+)/$', 'apps.application.views.users_change_password', name='app_userschangepassword'),

                       url(r'^redes-de-protecao/tipos/$', 'apps.application.views.typesprotectionnetwork_list', name='app_typesprotectionnetworklist'),
                       url(r'^redes-de-protecao/tipos/adicionar/$', 'apps.application.views.typesprotectionnetwork_add', name='app_typesprotectionnetworkadd'),
                       url(r'^redes-de-protecao/tipos/editar/(?P<id>[\w-]+)/$', 'apps.application.views.typesprotectionnetwork_edit', name='app_typesprotectionnetworkedit'),
                       url(r'^redes-de-protecao/tipos/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.typesprotectionnetwork_del', name='app_typesprotectionnetworkdel'),

                       url(r'^redes-de-protecao/$', 'apps.application.views.protectionnetwork_list', name='app_protectionnetworklist'),
                       url(r'^redes-de-protecao/adicionar/$', 'apps.application.views.protectionnetwork_add', name='app_protectionnetworkadd'),
                       url(r'^redes-de-protecao/editar/(?P<id>[\w-]+)/$', 'apps.application.views.protectionnetwork_edit', name='app_protectionnetworkedit'),
                       url(r'^redes-de-protecao/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.protectionnetwork_del', name='app_protectionnetworkdel'),

                       url(r'^tipos-de-violacao/$', 'apps.application.views.typesviolation_list', name='app_typesviolationlist'),
                       url(r'^tipos-de-violacao/adicionar/$', 'apps.application.views.typesviolation_add', name='app_typesviolationadd'),
                       url(r'^tipos-de-violacao/editar/(?P<id>[\w-]+)/$', 'apps.application.views.typesviolation_edit', name='app_typesviolationedit'),
                       url(r'^tipos-de-violacao/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.typesviolation_del', name='app_typesviolationedel'),

                       url(r'^feedback/$', 'apps.application.views.feedback', name='app_feedback'),
                       url(r'^feedback/resolvido/(?P<id>[\w-]+)/$', 'apps.application.views.feedback_as_resolved', name='app_feedback_as_resolved'),

                       url(r'^sair/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='app_logout'),
                       )

protejabrasil/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                           'document_root': settings.MEDIA_ROOT}),
                       (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                           'document_root': settings.STATIC_ROOT}),

                       url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                       url(r'^api/v1/docs/', include('rest_framework_swagger.urls')),
                       url(r'^api/v1/', include('apps.api.v1.urls')),
                       url(r'^api/v2/', include('apps.api.v2.urls')),
                       url(r'^', include('apps.application.urls'), name='application'),

                       )

apps/application/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from geoposition.forms import GeopositionField
from apps.protectionnetwork.models import Type, ProtectionNetwork
from apps.theme.models import Theme
from apps.uf.models import UF
from apps.user.models import Users
from sorl.thumbnail.fields import ImageField
from apps.violation.models import TypeViolation, TypeViolationInternationalization

__author__ = 'teehamaral'


class LoginUserForm(forms.Form):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Usuário',
                'required': '',
                'class': 'form-control',
            }
        ))
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Senha',
                'required': '',
                'class': 'form-control',
            }
        ))

    def clean(self):
        if not authenticate(username=self.cleaned_data.get('username', ''),
                            password=self.cleaned_data.get('password', '')):
            raise ValidationError('Usuário ou senha incorreta.')


class AddUserForm(forms.ModelForm):
    TYPES = [
        ('theme_admin', 'Administrador do tema'),
        ('theme_user', 'Usuário do tema')
    ]

    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Usado para entrar no sistema',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Nome',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Sobrenome',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'E-mail',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Senha',
                'required': '',
                'class': 'form-control'
            }
        ))
    confirm_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirmação da senha',
                'required': '',
                'class': 'form-control'
            }
        ))
    institution = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Instuição',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        )
    )
    departament = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Departamento',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    cell = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(00) 9 0000-0000',
                'autocomplete': 'off',
                'class': 'form-control celular'
            }
        ))
    phone = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(00) 9 0000-0000',
                'autocomplete': 'off',
                'class': 'form-control telefone'
            }
        ))
    type = forms.ChoiceField(
        required=False,
        choices=TYPES,
        widget=forms.RadioSelect()
    )
    is_active = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput()
    )

    class Meta:
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'is_active', 'institution',
                  'departament', 'cell', 'phone', 'type', ]
        model = Users

    def clean(self):
        list_group = ('theme_admin', 'theme_user', u'')
        if not self.cleaned_data.get(u'type') in list_group:
            raise ValidationError('Selecione um tipo válido.')

        if self.cleaned_data.get('password') != self.cleaned_data.get('confirm_password'):
            raise ValidationError('Senha e confirmação de senha não conferem')

        user_app = Users.objects.filter(username=self.cleaned_data.get(u'username'))
        if user_app.count() > 0:
            raise ValidationError('Este username já foi cadastrado anteriormente.')

        return self.cleaned_data


class EditUserForm(forms.ModelForm):
    TYPES = [
        ('theme_admin', 'Administrador do tema'),
        ('theme_user', 'Usuário do tema')
    ]

    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Nome',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Sobrenome',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'E-mail',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    institution = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Instuição',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        )
    )
    departament = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Departamento',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    cell = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(00) 9 0000-0000',
                'autocomplete': 'off',
                'class': 'form-control celular'
            }
        ))
    phone = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(00) 9 0000-0000',
                'autocomplete': 'off',
                'class': 'form-control telefone'
            }
        ))
    type = forms.ChoiceField(
        required=False,
        choices=TYPES,
        widget=forms.RadioSelect()
    )
    is_active = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput()
    )

    class Meta:
        fields = ['first_name', 'last_name', 'email', 'is_active', 'institution',
                  'departament', 'cell', 'phone', 'type', ]
        model = Users


class ChangePasswordForm(forms.Form):
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Senha',
                'required': '',
                'class': 'form-control'
            }
        ))
    confirm_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirmação da senha',
                'required': '',
                'class': 'form-control'
            }
        ))

    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('confirm_password'):
            raise ValidationError('Senha e confirmação de senha não conferem')

        return self.cleaned_data


class ForgotPasswordForm(forms.Form):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Usuário cadastrado no sistema',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))

    def clean(self):
        user = Users.objects.filter(username=self.cleaned_data.get('username'))
        if user.count() > 0:
            user = user[0]
            if not user.email:
                raise ValidationError(
                    'O usuário informado foi encontrado, mas não há um e-mail cadastrado para enviarmos a nova senha. Por favor, entre em contato com o administrador do sistema.')
        else:
            raise ValidationError('O usuário informado não consta em nossa base de dados.')

        return self.cleaned_data


class AddTypeProctetionNetworkForm(forms.ModelForm):
    color = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off',
                'class': "form-control color{hash:true, pickerFaceColor:'transparent', pickerFace:3, pickerBorder:0, pickerInsetColor:'black'}"
            }
        ))
    icon = ImageField(blank=True, null=True)

    class Meta:
        model = Type
        fields = ['color', 'icon']

    def clean(self):
        return self.cleaned_data


class AddTypeProctetionNetworkInternationalizationForm(forms.Form):
    name_pt = forms.CharField(
        required=True,
        label='Nome *',
        widget=forms.TextInput(

templates/application/typesprotectionnetwork/add.html
{% extends 'application/base.html' %}

{% block title %}Adicionar tipo de rede proteção - Proteja Brasil{% endblock %}

{% block extracss %}
    <style>
        .tab-content {
            margin: 20px 0 0 0;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="row">
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'app_typesprotectionnetworklist' %}">
                    Tipos de rede proteção
                </a>
            </li>
            <li class="active">Adicionar</li>
        </ul>
    </div>

    <div class="row">
        <div class="container col-lg-6" style="float: none;">

            <h2>
                Adicionar tipo de rede proteção

                <a href="javascript:history.back();" class="back">
                    <i class="glyphicon glyphicon-chevron-left"></i> voltar
                </a>

            </h2>

            <form class="form-horizontal" action="{% url 'app_typesprotectionnetworkadd' %}" method="POST"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#pt" data-toggle="tab" aria-expanded="true">Português</a></li>
                        <li class=""><a href="#en" data-toggle="tab" aria-expanded="false">English</a></li>
                        <li class=""><a href="#es" data-toggle="tab" aria-expanded="false">Español</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade active in" id="pt">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_pt">{{ form_info.name_pt.label }}</label>
                                    {{ form_info.name_pt }}
                                    {{ form_info.name_pt.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="en">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_en">{{ form_info.name_en.label }}</label>
                                    {{ form_info.name_en }}
                                    {{ form_info.name_en.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="es">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_es">{{ form_info.name_es.label }}</label>
                                    {{ form_info.name_es }}
                                    {{ form_info.name_es.errors }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-6">
                            <label for="id_color">Cor</label>
                            {{ form.color }}
                            {{ form.color.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_icon">Ícone</label>
                            {{ form.icon }}
                            {{ form.icon.errors }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-primary right">Salvar</button>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
    </div>



{% endblock %}

templates/application/typesprotectionnetwork/edit.html
{% extends 'application/base.html' %}

{% block title %}Editar tipo de rede proteção - Proteja Brasil{% endblock %}

{% block extracss %}
    <style>
        .tab-content {
            margin: 20px 0 0 0;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="row">
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'app_typesprotectionnetworklist' %}">
                    Tipos de rede proteção
                </a>
            </li>
            <li class="active">Editar</li>
        </ul>
    </div>

    <div class="row">
        <div class="container col-lg-6" style="float: none;">

            <h2>
                Editar tipo de rede proteção

                <a href="javascript:history.back();" class="back">
                    <i class="glyphicon glyphicon-chevron-left"></i> voltar
                </a>

            </h2>

            <form class="form-horizontal" action="{% url 'app_typesprotectionnetworkedit' current_type.id %}"
                  method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#pt" data-toggle="tab" aria-expanded="true">Português</a></li>
                        <li class=""><a href="#en" data-toggle="tab" aria-expanded="false">English</a></li>
                        <li class=""><a href="#es" data-toggle="tab" aria-expanded="false">Español</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade active in" id="pt">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_pt">{{ form_info.name_pt.label }}</label>
                                    {{ form_info.name_pt }}
                                    {{ form_info.name_pt.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="en">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_en">{{ form_info.name_en.label }}</label>
                                    {{ form_info.name_en }}
                                    {{ form_info.name_en.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="es">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_es">{{ form_info.name_es.label }}</label>
                                    {{ form_info.name_es }}
                                    {{ form_info.name_es.errors }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-6">
                            <label for="id_color">Cor</label>
                            {{ form.color }}
                            {{ form.color.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_icon">Ícone</label>
                            {{ form.icon }}
                            {{ form.icon.errors }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-primary right">Salvar</button>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
    </div>



{% endblock %}