apps/application/urls.py
# -*- coding: utf-8 -*-

__author__ = u'teehamaral'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^$', 'apps.application.views.login', name='app_login'),

                       url(r'^importar-redes-de-protecao/$', 'apps.application.views.import_protectionnetworks', name='app_import_protectionnetworks'),

                       url(r'^esqueceu-a-senha/$', 'apps.application.views.forgotpassword', name='app_forgotpassword'),
                       url(r'^dashboard/$', 'apps.application.views.dashboard', name='app_dashboard'),

                       url(r'^usuarios/$', 'apps.application.views.users_list', name='app_userslist'),
                       url(r'^usuarios/adicionar/$', 'apps.application.views.users_add', name='app_usersadd'),
                       url(r'^usuarios/editar/(?P<id>[\w-]+)/$', 'apps.application.views.users_edit', name='app_usersedit'),
                       url(r'^usuarios/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.users_del', name='app_usersdel'),
                       url(r'^usuarios/alterar-senha/(?P<id>[\w-]+)/$', 'apps.application.views.users_change_password', name='app_userschangepassword'),

                       url(r'^redes-de-protecao/tipos/$', 'apps.application.views.typesprotectionnetwork_list', name='app_typesprotectionnetworklist'),
                       url(r'^redes-de-protecao/tipos/adicionar/$', 'apps.application.views.typesprotectionnetwork_add', name='app_typesprotectionnetworkadd'),
                       url(r'^redes-de-protecao/tipos/editar/(?P<id>[\w-]+)/$', 'apps.application.views.typesprotectionnetwork_edit', name='app_typesprotectionnetworkedit'),
                       url(r'^redes-de-protecao/tipos/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.typesprotectionnetwork_del', name='app_typesprotectionnetworkdel'),

                       url(r'^redes-de-protecao/$', 'apps.application.views.protectionnetwork_list', name='app_protectionnetworklist'),
                       url(r'^redes-de-protecao/adicionar/$', 'apps.application.views.protectionnetwork_add', name='app_protectionnetworkadd'),
                       url(r'^redes-de-protecao/editar/(?P<id>[\w-]+)/$', 'apps.application.views.protectionnetwork_edit', name='app_protectionnetworkedit'),
                       url(r'^redes-de-protecao/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.protectionnetwork_del', name='app_protectionnetworkdel'),

                       url(r'^tipos-de-violacao/$', 'apps.application.views.typesviolation_list', name='app_typesviolationlist'),
                       url(r'^tipos-de-violacao/adicionar/$', 'apps.application.views.typesviolation_add', name='app_typesviolationadd'),
                       url(r'^tipos-de-violacao/editar/(?P<id>[\w-]+)/$', 'apps.application.views.typesviolation_edit', name='app_typesviolationedit'),
                       url(r'^tipos-de-violacao/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.typesviolation_del', name='app_typesviolationedel'),

                       url(r'^feedback/$', 'apps.application.views.feedback', name='app_feedback'),
                       url(r'^feedback/resolvido/(?P<id>[\w-]+)/$', 'apps.application.views.feedback_as_resolved', name='app_feedback_as_resolved'),

                       url(r'^sair/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='app_logout'),
                       )

protejabrasil/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                           'document_root': settings.MEDIA_ROOT}),
                       (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                           'document_root': settings.STATIC_ROOT}),

                       url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                       url(r'^api/v1/docs/', include('rest_framework_swagger.urls')),
                       url(r'^api/v1/', include('apps.api.v1.urls')),
                       url(r'^api/v2/', include('apps.api.v2.urls')),
                       url(r'^', include('apps.application.urls'), name='application'),

                       )

apps/protectionnetwork/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.shortcuts import get_object_or_404
from sorl.thumbnail.fields import ImageField
from geoposition.fields import GeopositionField
from apps.theme.models import Theme
from apps.uf.models import UF


class TypeManager(models.Manager):
    def get_search(self, search):
        return super(TypeManager, self).get_queryset().filter(search).order_by('-id')


class Type(models.Model):
    name = models.CharField(verbose_name='Nome', help_text='Informe o nome do tipo da rede de proteção',
                            max_length=255, unique=True, )
    color = models.CharField(verbose_name='Cor', help_text='Informe o código hexadecimal da cor', max_length=10,
                             null=True, blank=True, )
    icon = ImageField(verbose_name='Ícone', help_text='Selecione um ícone', max_length=255,
                      upload_to='protectionnetwork/types', null=True, blank=True, )
    date_joined = models.DateTimeField(verbose_name='Data de cadastro', help_text='Data de cadastro',
                                       auto_now_add=True, editable=False, null=True, )
    objects = TypeManager()

    def __str__(self):
        return '{0}'.format(self.name)

    class Meta:
        verbose_name = 'Tipo'
        verbose_name_plural = 'Tipos'

    def get_icon(self):
        from protejabrasil import settings
        from sorl.thumbnail import get_thumbnail

        if self.icon:
            return 'http://{0}{1}'.format(settings.SITE_URL,
                                          get_thumbnail(self.icon, '60', quality=100, format='PNG').url)
        else:
            return None

    def get_default_language(self):
        return 'pt'


class TypeInternationalizationManager(models.Manager):
    def create(self, type_id, language, name):
        item = self.model(
            type_id=type_id,
            language=language,
            name=name
        )
        item.save(using=self._db)
        return item


class TypeInternationalization(models.Model):
    LANGUAGES = (
        ('pt', 'Português'),
        ('en', 'English'),
        ('es', 'Español'),
    )
    type = models.ForeignKey(Type, verbose_name='Tipo', related_name='info', )
    language = models.CharField(choices=LANGUAGES, verbose_name='Idioma', max_length=2, default='pt', )
    name = models.CharField(verbose_name='Nome', max_length=255, )
    date_joined = models.DateTimeField(verbose_name='Data de cadastro', help_text='Data de cadastro', auto_now_add=True, editable=False)
    objects = TypeInternationalizationManager()

    def __str__(self):
        return '{0}'.format(self.name)

    class Meta:
        verbose_name = 'Internacionalização'
        verbose_name_plural = verbose_name
        ordering = ('-language',)


class ProtectionNetworkManager(models.Manager):
    def get_search(self, user, search):
        states = user.states.all()
        states = [s.uf_id for s in states]

        themes = user.themes.all()
        themes = [t.theme_id for t in themes]

        queryset = super(ProtectionNetworkManager, self).get_queryset().filter(search).order_by('-id')

        filter = []

        for item in queryset:
            for ut in item.themes.all():
                theme = get_object_or_404(Theme, id=ut.theme_id)
                if theme.id in themes and item not in filter:
                    filter.append(item)

        new_filter = []

        for item_ in filter:
            state = get_object_or_404(UF, id=item_.state_id)
            if state.id in states and item_ not in new_filter:
                new_filter.append(item_)

        return new_filter

    def add_protectionnetwork(self, type, name, position, zipcode, address, neighborhood, city, state, contact, phone1,
                              phone2, email):
        item = self.model(
            type=type,
            name=name,
            position=position,
            zipcode=zipcode,
            address=address,
            neighborhood=neighborhood,
            city=city,
            state=state,
            contact=contact,
            phone1=phone1,
            phone2=phone2,
            email=email,
        )
        item.save(using=self._db)
        return item


class ProtectionNetwork(models.Model):
    type = models.ForeignKey(Type, verbose_name='Tipo', help_text='Selecione o tipo da rede de proteção', )
    name = models.CharField(verbose_name='Nome', max_length=255, )
    position = GeopositionField(verbose_name='Coordenadas', help_text='Selecione a localização no mapa.',
                                max_length=100, )
    zipcode = models.CharField(verbose_name='CEP', max_length=20, )
    address = models.CharField(verbose_name='Logradouro', max_length=255, )
    neighborhood = models.CharField(verbose_name='Bairro', max_length=255, )
    city = models.CharField(verbose_name='Cidade', max_length=255, )
    state = models.ForeignKey(UF, verbose_name='Estado', max_length=255, )
    contact = models.CharField(verbose_name='Contato', max_length=255, null=True, blank=True, )
    phone1 = models.CharField(verbose_name='Telefone 1', max_length=20, )
    phone2 = models.CharField(verbose_name='Telefone 2', max_length=20, null=True, blank=True, )
    email = models.CharField(verbose_name='E-mail', max_length=255, null=True, blank=True, )
    schedule = models.TextField(verbose_name='Horário', null=True, blank=True, )
    date_joined = models.DateTimeField(verbose_name='Data de cadastro', help_text='Data de cadastro',
                                       auto_now_add=True, editable=False)
    objects = ProtectionNetworkManager()

    def __str__(self):
        return '{0}'.format(self.name)

    class Meta:
        verbose_name = 'Rede de proteção'
        verbose_name_plural = 'Redes de proteção'

    def get_themes(self):
        all = self.themes.all()

        themes = []

        for theme in all:
            them = {}
            them['id'] = theme.theme.id
            them['name'] = theme.theme.title
            them['icon'] = theme.theme.get_icon()
            them['color'] = theme.theme.color
            them['description'] = theme.theme.description
            them['sondha_id'] = theme.theme.sondha_id
            themes.append(them)

        return themes

    def get_day(self):
        return self.operatingdays.all()

    def get_type(self):
        try:
            type_ = Type.objects.get(id=self.type.id)

            type = {}
            type['id'] = type_.id
            type['name'] = type_.name
            type['color'] = type_.color
            type['icon'] = type_.get_icon()

        except:
            type = None

        return type

    def get_state(self):
        try:
            state_ = UF.objects.get(id=self.state.id)

            state = {}
            state['initials'] = state_.initials
            state['title'] = state_.title

        except:
            state = None

        return state

    def get_position(self):
        try:
            position = {}
            position['lat'] = self.position.latitude
            position['long'] = self.position.longitude

        except:
            position = None

        return position

    def get_default_language(self):
        return 'pt'


class ProtectionNetworkInternationalizationManager(models.Manager):
    def create(self, protectionnetwork_id, language, name):
        item = self.model(
            protectionnetwork_id=protectionnetwork_id,
            language=language,
            name=name
        )
        item.save(using=self._db)
        return item


class ProtectionNetworkInternationalization(models.Model):
    LANGUAGES = (
        ('pt', 'Português'),
        ('en', 'English'),
        ('es', 'Español'),
    )
    protectionnetwork = models.ForeignKey(ProtectionNetwork, verbose_name='Rede de proteção', related_name='info', )
    language = models.CharField(choices=LANGUAGES, verbose_name='Idioma', max_length=2, default='pt', )
    name = models.CharField(verbose_name='Nome', max_length=255, )
    date_joined = models.DateTimeField(verbose_name='Data de cadastro', help_text='Data de cadastro', auto_now_add=True, editable=False)
    objects = ProtectionNetworkInternationalizationManager()

    def __str__(self):
        return '{0}'.format(self.name)

    class Meta:
        verbose_name = 'Internacionalização'
        verbose_name_plural = verbose_name
        ordering = ('-language',)


class ThemeProtectionNetworkManager(models.Manager):
    def add_theme_protectionnetwork(self, protectionnetwork, theme):
        item = self.model(
            protectionnetwork=protectionnetwork,
            theme=theme,
        )
        item.save(using=self._db)
        return item


class ThemeProtectionNetwork(models.Model):
    protectionnetwork = models.ForeignKey(ProtectionNetwork, verbose_name='Rede de proteção', related_name='themes', )
    theme = models.ForeignKey(Theme, verbose_name='Tema', )
    objects = ThemeProtectionNetworkManager()

    def __str__(self):
        return '{0}'.format(self.theme)

    class Meta:
        verbose_name = 'Tema'
        verbose_name_plural = 'Temas'


class OperatingDaysProtectionNetworkManager(models.Manager):
    def add_operatingdays_protectionnetwork(self, protectionnetwork, day):
        item = self.model(
            protectionnetwork=protectionnetwork,
            day=day,
        )
        item.save(using=self._db)
        return item


class OperatingDaysProtectionNetwork(models.Model):
    DAYS = (
        ('sunday', 'Domingo'),
        ('monday', 'Segunda-feira'),
        ('tuesday', 'Terça-feira'),
        ('wednesday', 'Quarta-feira'),
        ('thursday', 'Quinta-feira'),
        ('friday', 'Sexta-feira'),
        ('saturday', 'Sábado'),
    )

    protectionnetwork = models.ForeignKey(ProtectionNetwork, verbose_name='Rede de proteção',
                                          related_name='operatingdays', )

templates/application/protectionnetwork/add.html
{% extends 'application/base.html' %}

{% block title %}Redes de proteção - Proteja Brasil{% endblock %}

{% block extracss %}
    <style>
        .tab-content {
            margin: 20px 0 0 0;
        }
    </style>
{% endblock %}

{% block extrajs %}
    {{ form.media }}

    <script>
        $(document).ready(function () {
            $(".geoposition-widget").on("change click mousemove mouseout mouseenter", function () {
                var address_full = $('.geoposition-address').text();

                if (address_full.length > 0) {
                    address_full = address_full.split(",");

                    if (address_full.length == 5) {

                        var address = address_full[0];
                        var cep = address_full[3];
                        cep = cep.replace(' ', '');

                        if (cep) {
                            if (cep.length == 9) {
                                cep = address_full[3];
                            } else {
                                cep = ' ';
                            }
                        }

                        var city_full = address_full[2];
                        city_full = city_full.split("-");
                        var city = city_full[0].replace(' ', '');

                        var neighborhood_full = address_full[1];
                        neighborhood_full = neighborhood_full.split("-");
                        neighborhood_full = neighborhood_full.reverse();
                        var neighborhood = neighborhood_full[0].replace(' ', '');

                        $('#id_address').attr('value', address);
                        $('#id_zipcode').attr('value', cep);
                        $('#id_neighborhood').attr('value', neighborhood);
                        $('#id_city').attr('value', city);

                    } else {
                        $('#id_address').attr('value', '');
                        $('#id_zipcode').attr('value', '');
                        $('#id_neighborhood').attr('value', '');
                        $('#id_city').attr('value', '');
                    }

                }

            });
        });
    </script>

{% endblock %}

{% block content %}

    <div class="row">
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'app_protectionnetworklist' %}">
                    Redes de proteção
                </a>
            </li>
            <li class="active">Adicionar</li>
        </ul>
    </div>

    <div class="row">
        <div class="container col-lg-6" style="float: none;">

            <h2>
                Adicionar rede de proteção

                <a href="javascript:history.back();" class="back">
                    <i class="glyphicon glyphicon-chevron-left"></i> voltar
                </a>

            </h2>

            <form class="form-horizontal" action="{% url 'app_protectionnetworkadd' %}" method="POST"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#pt" data-toggle="tab" aria-expanded="true">Português</a></li>
                        <li class=""><a href="#en" data-toggle="tab" aria-expanded="false">English</a></li>
                        <li class=""><a href="#es" data-toggle="tab" aria-expanded="false">Español</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade active in" id="pt">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_es">{{ form_info.name_pt.label }}</label>
                                    {{ form_info.name_pt }}
                                    {{ form_info.name_pt.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="en">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_en">{{ form_info.name_en.label }}</label>
                                    {{ form_info.name_en }}
                                    {{ form_info.name_en.errors }}
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="es">
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_es">{{ form_info.name_es.label }}</label>
                                    {{ form_info.name_es }}
                                    {{ form_info.name_es.errors }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_type">Tipo *</label>
                            {{ form.type }}
                            {{ form.type.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="themes">Temas *</label>
                            <select name="themes" multiple id="themes" class="form-control" required>
                                {% for them in themes %}
                                    <option value="{{ them.theme_id }}">{{ them }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_position">Localização *</label>
                            {{ form.position }}
                            {{ form.position.errors }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_address">Logradouro *</label>
                            {{ form.address }}
                            {{ form.address.errors }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-md-6">
                                    <label for="id_zipcode">CEP *</label>
                                    {{ form.zipcode }}
                                    {{ form.zipcode.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_neighborhood">Bairro *</label>
                                    {{ form.neighborhood }}
                                    {{ form.neighborhood.errors }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-md-6">
                                    <label for="id_city">Cidade *</label>
                                    {{ form.city }}
                                    {{ form.city.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_state">Estado *</label>
                                    {{ form.state }}
                                    {{ form.state.errors }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_contact">Contato</label>
                            {{ form.contact }}
                            {{ form.contact.errors }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-md-6">
                                    <label for="id_phone1">Telefone 1 *</label>
                                    {{ form.phone1 }}
                                    {{ form.phone1.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_phone2">Telefone 2</label>
                                    {{ form.phone2 }}
                                    {{ form.phone2.errors }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_email">E-mail</label>
                            {{ form.email }}
                            {{ form.email.errors }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-md-6">
                                    <label for="days">Dias de atendimento *</label>
                                    <select name="days" multiple id="days" class="form-control" required>
                                        {% for day in days %}
                                            <option value="{{ day.0 }}">{{ day.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-md-6">
                                    <label for="id_schedule">Horário de funcionamento</label>
                                    {{ form.schedule }}
                                    {{ form.schedule.errors }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-primary right">Salvar</button>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
    </div>

{% endblock %}