apps/application/urls.py
# -*- coding: utf-8 -*-

__author__ = u'teehamaral'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^$', 'apps.application.views.login', name='app_login'),

                       url(r'^importar-redes-de-protecao/$', 'apps.application.views.import_protectionnetworks', name='app_import_protectionnetworks'),

                       url(r'^esqueceu-a-senha/$', 'apps.application.views.forgotpassword', name='app_forgotpassword'),
                       url(r'^dashboard/$', 'apps.application.views.dashboard', name='app_dashboard'),

                       url(r'^usuarios/$', 'apps.application.views.users_list', name='app_userslist'),
                       url(r'^usuarios/adicionar/$', 'apps.application.views.users_add', name='app_usersadd'),
                       url(r'^usuarios/editar/(?P<id>[\w-]+)/$', 'apps.application.views.users_edit', name='app_usersedit'),
                       url(r'^usuarios/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.users_del', name='app_usersdel'),
                       url(r'^usuarios/alterar-senha/(?P<id>[\w-]+)/$', 'apps.application.views.users_change_password', name='app_userschangepassword'),

                       url(r'^redes-de-protecao/tipos/$', 'apps.application.views.typesprotectionnetwork_list', name='app_typesprotectionnetworklist'),
                       url(r'^redes-de-protecao/tipos/adicionar/$', 'apps.application.views.typesprotectionnetwork_add', name='app_typesprotectionnetworkadd'),
                       url(r'^redes-de-protecao/tipos/editar/(?P<id>[\w-]+)/$', 'apps.application.views.typesprotectionnetwork_edit', name='app_typesprotectionnetworkedit'),
                       url(r'^redes-de-protecao/tipos/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.typesprotectionnetwork_del', name='app_typesprotectionnetworkdel'),

                       url(r'^redes-de-protecao/$', 'apps.application.views.protectionnetwork_list', name='app_protectionnetworklist'),
                       url(r'^redes-de-protecao/adicionar/$', 'apps.application.views.protectionnetwork_add', name='app_protectionnetworkadd'),
                       url(r'^redes-de-protecao/editar/(?P<id>[\w-]+)/$', 'apps.application.views.protectionnetwork_edit', name='app_protectionnetworkedit'),
                       url(r'^redes-de-protecao/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.protectionnetwork_del', name='app_protectionnetworkdel'),

                       url(r'^tipos-de-violacao/$', 'apps.application.views.typesviolation_list', name='app_typesviolationlist'),
                       url(r'^tipos-de-violacao/adicionar/$', 'apps.application.views.typesviolation_add', name='app_typesviolationadd'),
                       url(r'^tipos-de-violacao/editar/(?P<id>[\w-]+)/$', 'apps.application.views.typesviolation_edit', name='app_typesviolationedit'),
                       url(r'^tipos-de-violacao/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.typesviolation_del', name='app_typesviolationedel'),

                       url(r'^feedback/$', 'apps.application.views.feedback', name='app_feedback'),
                       url(r'^feedback/resolvido/(?P<id>[\w-]+)/$', 'apps.application.views.feedback_as_resolved', name='app_feedback_as_resolved'),

                       url(r'^sair/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='app_logout'),
                       )

protejabrasil/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                           'document_root': settings.MEDIA_ROOT}),
                       (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                           'document_root': settings.STATIC_ROOT}),

                       url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                       url(r'^api/v1/docs/', include('rest_framework_swagger.urls')),
                       url(r'^api/v1/', include('apps.api.v1.urls')),
                       url(r'^api/v2/', include('apps.api.v2.urls')),
                       url(r'^', include('apps.application.urls'), name='application'),

                       )

apps/user/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser, PermissionsMixin)
from django.shortcuts import get_object_or_404
from django.utils import timezone
from apps.permission.models import Permission
from apps.theme.models import Theme
from apps.uf.models import UF


class UsersManager(BaseUserManager):
    def create_user(self, username, first_name, last_name, email, password=None):
        if not username:
            raise ValueError('Os usuários devem ter um username.')

        user = self.model(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=self.normalize_email(email)
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, first_name, last_name, email, password):
        user = self.create_user(username,
                                first_name=first_name,
                                last_name=last_name,
                                email=email,
                                password=password
                                )
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user

    def get_search(self, user, search):
        states = user.states.all()
        states = [s.uf_id for s in states]

        themes = user.themes.all()
        themes = [t.theme_id for t in themes]

        queryset = super(UsersManager, self).get_queryset().filter(search).order_by('-id')

        filter = []

        for user in queryset:
            for ut in user.themes.all():
                theme = get_object_or_404(Theme, id=ut.theme_id)
                if theme.id in themes and user not in filter:
                    filter.append(user)

        new_filter = []

        for user_ in filter:
            for us in user_.states.all():
                state = get_object_or_404(UF, id=us.uf_id)
                if state.id in states and user_ not in new_filter:
                    new_filter.append(user_)

        return new_filter


class Users(AbstractBaseUser, PermissionsMixin):
    TYPE = (
        ('theme_admin', 'Administrador do tema',),
        ('theme_user', 'Usuário do tema',),
        ('partner', 'Parceiro',),
    )

    user_auth = models.ForeignKey('Users', verbose_name='Usuário de cadastro', help_text='Usuário que o cadastro',
                                  null=True, blank=True, related_name='user_insert')
    username = models.CharField(verbose_name='Username', help_text='Username do usuário relacionado', max_length=30,
                                unique=True, )
    email = models.CharField(verbose_name='E-mail', help_text='E-mail do usuário relacionado', max_length=255, )
    first_name = models.CharField(verbose_name='Nome', help_text='Nome do usuário relacionado',
                                  max_length=255, )
    last_name = models.CharField(verbose_name='Sobrenome', help_text='Sobrenome do usuário relacionado',
                                 max_length=255, )
    phone = models.CharField(verbose_name='Telefone', max_length=100, null=True, blank=True, )
    cell = models.CharField(verbose_name='Celular', max_length=100, null=True, blank=True, )
    institution = models.CharField(verbose_name='Instituição', max_length=255, null=True, blank=True, )
    departament = models.CharField(verbose_name='departamento', max_length=255, null=True, blank=True, )
    type = models.CharField(verbose_name='Tipo', help_text='Selecione o tipo de usuário', choices=TYPE,
                            max_length=20, )
    is_active = models.BooleanField(default=True, verbose_name='Ativo',
                                    help_text='Determina se este usuário deve ser tratado como ativo. Desmarque esta opção em vez de excluir contas.')
    is_staff = models.BooleanField(default=False, verbose_name='Membro da equipe',
                                   help_text='Determina se o usuário pode acessar o Administrador.')

    date_joined = models.DateTimeField('Data de cadastro', default=timezone.now)

    objects = UsersManager()

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['first_name', 'last_name', 'email', ]

    def get_full_name(self):
        return u"{0} {1}".format(self.first_name, self.last_name)

    get_full_name.short_description = 'Nome completo'

    def get_short_name(self):
        return '{0}'.format(self.first_name)

    get_short_name.short_description = 'Nome'

    def __str__(self):
        return u"{0} {1}".format(self.first_name, self.last_name)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'


class UsersPermissionManager(models.Manager):
    def add_permission_user(self, user, permission):
        item = self.model(
            user=user,
            permission=permission
        )

        item.save(using=self._db)
        return item


class UsersPermission(models.Model):
    user = models.ForeignKey(Users, verbose_name='Usuário', related_name='permissions')
    permission = models.ForeignKey(Permission, verbose_name='Permissão', )
    objects = UsersPermissionManager()

    def __unicode__(self):
        return '{0}'.format(self.user)

    class Meta:
        verbose_name = 'Permissão do usuário'
        verbose_name_plural = 'Permissões do usuário'


class UsersThemeManager(models.Manager):
    def add_theme_user(self, user, theme):
        item = self.model(
            user=user,
            theme=theme
        )

        item.save(using=self._db)
        return item


class UsersTheme(models.Model):
    user = models.ForeignKey(Users, verbose_name='Usuário', related_name='themes')
    theme = models.ForeignKey(Theme, verbose_name='Tema', )
    objects = UsersThemeManager()

    def __str__(self):
        return '{0}'.format(self.theme)

    class Meta:
        verbose_name = 'Tema do usuário'
        verbose_name_plural = 'Temas do usuário'


class UsersUFManager(models.Manager):
    def add_uf_user(self, user, uf):
        item = self.model(
            user=user,
            uf=uf
        )

        item.save(using=self._db)
        return item


class UsersUF(models.Model):
    user = models.ForeignKey(Users, verbose_name='Usuário', related_name='states')
    uf = models.ForeignKey(UF, verbose_name='UF', help_text='Selecione um estado que o usuário pertence', )
    objects = UsersUFManager()

    def __str__(self):
        return '{0}'.format(self.uf)

    class Meta:
        verbose_name = 'UF do usuário'
        verbose_name_plural = 'UFs do usuário'

templates/application/users/add.html
{% extends 'application/base.html' %}

{% block title %}Adicionar usuário - Proteja Brasil{% endblock %}

{% block content %}

    <div class="row">
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'app_userslist' %}">
                    Usuários
                </a>
            </li>
            <li class="active">Adicionar</li>
        </ul>
    </div>

    <div class="row">
        <div class="container col-lg-6" style="float: none;">

            <h2>
                Adicionar usuário

                <a href="javascript:history.back();" class="back">
                    <i class="glyphicon glyphicon-chevron-left"></i> voltar
                </a>

            </h2>

            <form class="form-horizontal" action="{% url 'app_usersadd' %}" method="POST">
                {% csrf_token %}
                <fieldset>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_username">Usuário *</label>
                            {{ form_user.username }}
                            {{ form_user.username.errors }}
                            <span class="help-block">
                                30 caracteres ou menos. Somente letras, dígitos e @/./+/-/_
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_first_name">Nome *</label>
                                    {{ form_user.first_name }}
                                    {{ form_user.first_name.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_last_name">Sobrenome *</label>
                                    {{ form_user.last_name }}
                                    {{ form_user.last_name.errors }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_email">E-mail *</label>
                            {{ form_user.email }}
                            {{ form_user.email.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-md-6">
                                    <label for="id_password">Senha *</label>
                                    {{ form_user.password }}
                                    {{ form_user.password.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_confirm_password">Confirmação da senha *</label>
                                    {{ form_user.confirm_password }}
                                    {{ form_user.confirm_password.errors }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-md-6">
                                    <label for="id_institution">Instituição</label>
                                    {{ form_user.institution }}
                                    {{ form_user.institution.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_departament">Departamento</label>
                                    {{ form_user.departament }}
                                    {{ form_user.departament.errors }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-md-6">
                                    <label for="id_cell">Celular</label>
                                    {{ form_user.cell }}
                                    {{ form_user.cell.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_phone">Telefone</label>
                                    {{ form_user.phone }}
                                    {{ form_user.phone.errors }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="themes">Temas *</label>
                            <select name="themes" multiple id="themes" class="form-control" required>
                                {% for them in themes_user %}
                                    <option value="{{ them.theme_id }}">{{ them }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="uf">UF *</label>
                            <select name="uf" multiple id="uf" class="form-control" required>
                                {% for uf in uf_user %}
                                    <option value="{{ uf.uf_id }}">{{ uf }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    {% if request.user.type == 'theme_admin' or request.user.is_superuser %}
                        <div class="form-group">
                            <div class="col-lg-12">
                                {{ form_user.type }}
                                {{ form_user.type.errors }}
                            </div>
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="permissions">Permissões</label>
                            <select name="permissions" multiple id="permissions" class="form-control">
                                {% for perm in permissions %}
                                    <option value="{{ perm.id }}">{{ perm }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_is_active">
                                {{ form_user.is_active }} Ativo
                            </label>
                            {{ form_user.is_active.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-primary right">Salvar</button>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
    </div>



{% endblock %}

templates/application/users/change-password.html
{% extends 'application/base.html' %}

{% block title %}Alterar senha - Proteja Brasil{% endblock %}

{% block content %}
    <div class="row">
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'app_userslist' %}">
                    Usuários
                </a>
            </li>
            <li class="active">Alterar senha</li>
        </ul>
    </div>

    <div class="row">
        <div class="container col-lg-6" style="float: none;">

            <h2>
                Alterar senha

                <a href="javascript:history.back();" class="back">
                    <i class="glyphicon glyphicon-chevron-left"></i> voltar
                </a>

            </h2>

            <form class="form-horizontal" action="{% url 'app_userschangepassword' user.id %}" method="POST">
                {% csrf_token %}
                <fieldset>
                    {% if user != request.user %}
                        <div class="form-group">
                            <div class="col-lg-12">
                                <label for="">Usuário</label>
                                <input type="text" value="{{ user.username }}" readonly disabled
                                       class="form-control"/>
                            </div>
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-md-6">
                                    <label for="id_user-password">Senha *</label>
                                    {{ form.password }}
                                    {{ form.password.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_user-confirmacao">Confirmação da senha *</label>
                                    {{ form.confirm_password }}
                                    {{ form.confirm_password.errors }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-primary right">Salvar</button>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
    </div>
{% endblock %}

templates/application/users/edit.html
{% extends 'application/base.html' %}

{% block title %}Editar usuário - Proteja Brasil{% endblock %}

{% block content %}

    <div class="row">
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'app_userslist' %}">
                    Usuários
                </a>
            </li>
            <li class="active">Editar</li>
        </ul>
    </div>

    <div class="row">
        <div class="container col-lg-6" style="float: none;">

            <h2>
                Editar usuário

                <a href="javascript:history.back();" class="back">
                    <i class="glyphicon glyphicon-chevron-left"></i> voltar
                </a>

            </h2>

            <form class="form-horizontal" action="{% url 'app_usersedit' current_user.id %}" method="POST">
                {% csrf_token %}
                <fieldset>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_user-username">Usuário</label>
                            <input type="text" readonly disabled value="{{ current_user.username }}"
                                   class="form-control"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_first_name">Nome *</label>
                                    {{ form_user.first_name }}
                                    {{ form_user.first_name.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_last_name">Sobrenome *</label>
                                    {{ form_user.last_name }}
                                    {{ form_user.last_name.errors }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_email">E-mail *</label>
                            {{ form_user.email }}
                            {{ form_user.email.errors }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_institution">Instituição</label>
                                    {{ form_user.institution }}
                                    {{ form_user.institution.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_departament">Departamento</label>
                                    {{ form_user.departament }}
                                    {{ form_user.departament.errors }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_cell">Celular</label>
                                    {{ form_user.cell }}
                                    {{ form_user.cell.errors }}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_phone">Telefone</label>
                                    {{ form_user.phone }}
                                    {{ form_user.phone.errors }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="themes">Temas *</label>
                            <select name="themes" multiple id="themes" class="form-control" required>
                                {% for them in themes_user %}
                                    <option value="{{ them.theme_id }}"
                                            {% if them.theme_id in user_themes_id %}selected{% endif %}>{{ them }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="uf">UF *</label>
                            <select name="uf" multiple id="uf" class="form-control" required>
                                {% for uf in uf_user %}
                                    <option value="{{ uf.uf_id }}"
                                            {% if uf.uf_id in user_uf_id %}selected{% endif %}>{{ uf }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    {% if request.user.type == 'theme_admin' or request.user.is_superuser %}
                        <div class="form-group">
                            <div class="col-lg-12">
                                {{ form_user.type }}
                                {{ form_user.type.errors }}
                            </div>
                        </div>
                    {% endif %}

                    {% if request.user.type == 'theme_admin' or request.user.is_superuser %}
                        <div class="form-group">
                            <div class="col-lg-12">
                                <label for="permissions">Permissões</label>
                                <select name="permissions" multiple id="permissions" class="form-control">
                                    {% for perm in permissions %}
                                        <option value="{{ perm.id }}"
                                                {% if perm.id in user_permissions_id %}selected{% endif %}>{{ perm }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_is_active">
                                {{ form_user.is_active }} Ativo
                            </label>
                            {{ form_user.is_active.errors }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-primary right">Salvar</button>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
    </div>



{% endblock %}