apps/application/urls.py
# -*- coding: utf-8 -*-

__author__ = u'teehamaral'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^$', 'apps.application.views.login', name='app_login'),

                       url(r'^importar-redes-de-protecao/$', 'apps.application.views.import_protectionnetworks', name='app_import_protectionnetworks'),

                       url(r'^esqueceu-a-senha/$', 'apps.application.views.forgotpassword', name='app_forgotpassword'),
                       url(r'^dashboard/$', 'apps.application.views.dashboard', name='app_dashboard'),

                       url(r'^usuarios/$', 'apps.application.views.users_list', name='app_userslist'),
                       url(r'^usuarios/adicionar/$', 'apps.application.views.users_add', name='app_usersadd'),
                       url(r'^usuarios/editar/(?P<id>[\w-]+)/$', 'apps.application.views.users_edit', name='app_usersedit'),
                       url(r'^usuarios/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.users_del', name='app_usersdel'),
                       url(r'^usuarios/alterar-senha/(?P<id>[\w-]+)/$', 'apps.application.views.users_change_password', name='app_userschangepassword'),

                       url(r'^redes-de-protecao/tipos/$', 'apps.application.views.typesprotectionnetwork_list', name='app_typesprotectionnetworklist'),
                       url(r'^redes-de-protecao/tipos/adicionar/$', 'apps.application.views.typesprotectionnetwork_add', name='app_typesprotectionnetworkadd'),
                       url(r'^redes-de-protecao/tipos/editar/(?P<id>[\w-]+)/$', 'apps.application.views.typesprotectionnetwork_edit', name='app_typesprotectionnetworkedit'),
                       url(r'^redes-de-protecao/tipos/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.typesprotectionnetwork_del', name='app_typesprotectionnetworkdel'),

                       url(r'^redes-de-protecao/$', 'apps.application.views.protectionnetwork_list', name='app_protectionnetworklist'),
                       url(r'^redes-de-protecao/adicionar/$', 'apps.application.views.protectionnetwork_add', name='app_protectionnetworkadd'),
                       url(r'^redes-de-protecao/editar/(?P<id>[\w-]+)/$', 'apps.application.views.protectionnetwork_edit', name='app_protectionnetworkedit'),
                       url(r'^redes-de-protecao/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.protectionnetwork_del', name='app_protectionnetworkdel'),

                       url(r'^tipos-de-violacao/$', 'apps.application.views.typesviolation_list', name='app_typesviolationlist'),
                       url(r'^tipos-de-violacao/adicionar/$', 'apps.application.views.typesviolation_add', name='app_typesviolationadd'),
                       url(r'^tipos-de-violacao/editar/(?P<id>[\w-]+)/$', 'apps.application.views.typesviolation_edit', name='app_typesviolationedit'),
                       url(r'^tipos-de-violacao/excluir/(?P<id>[\w-]+)/$', 'apps.application.views.typesviolation_del', name='app_typesviolationedel'),

                       url(r'^feedback/$', 'apps.application.views.feedback', name='app_feedback'),
                       url(r'^feedback/resolvido/(?P<id>[\w-]+)/$', 'apps.application.views.feedback_as_resolved', name='app_feedback_as_resolved'),

                       url(r'^sair/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='app_logout'),
                       )

protejabrasil/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                           'document_root': settings.MEDIA_ROOT}),
                       (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                           'document_root': settings.STATIC_ROOT}),

                       url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                       url(r'^api/v1/docs/', include('rest_framework_swagger.urls')),
                       url(r'^api/v1/', include('apps.api.v1.urls')),
                       url(r'^api/v2/', include('apps.api.v2.urls')),
                       url(r'^', include('apps.application.urls'), name='application'),

                       )

apps/theme/models.py
from django.db import models
from sorl.thumbnail.fields import ImageField


class Theme(models.Model):
    title = models.CharField(verbose_name='Título', help_text='Insira o título do tema', max_length=255, null=True, blank=True, )
    color = models.CharField(verbose_name='Cor', help_text='Informe o código hexadecimal da cor', max_length=10, null=True, blank=True, )
    icon = ImageField(verbose_name='Ícone', help_text='Selecione um ícone', max_length=255, upload_to='themes/icons', null=True, blank=True, )
    description = models.TextField(verbose_name='Descrição', null=True, blank=True, )
    order = models.IntegerField(verbose_name='Ordem', null=True, blank=True, default=0, )
    date_joined = models.DateTimeField(verbose_name='Data de cadastro', help_text='Data de cadastro', auto_now_add=True, editable=False)
    sondha_id = models.IntegerField(verbose_name='ID do SONDHA', null=True, blank=True, )

    def __str__(self):
        return "{0}".format(self.title)

    class Meta:
        verbose_name = 'Tema'
        verbose_name_plural = 'Temas'

    def get_icon(self):
        from protejabrasil import settings
        from sorl.thumbnail import get_thumbnail

        if self.icon:
            return 'http://{0}{1}'.format(settings.SITE_URL, get_thumbnail(self.icon, '60', quality=100, format='PNG').url)
        else:
            return None

    def get_default_language(self):
        return 'pt'


class ThemeInternationalizationManager(models.Manager):
    def create(self, theme_id, language, title, description):
        item = self.model(
            theme_id=theme_id,
            language=language,
            title=title,
            description=description
        )
        item.save(using=self._db)
        return item


class ThemeInternationalization(models.Model):
    LANGUAGES = (
        ('pt', 'Português'),
        ('en', 'English'),
        ('es', 'Español'),
    )
    theme = models.ForeignKey(Theme, verbose_name='Tema', help_text='Tema', related_name='info', )
    language = models.CharField(choices=LANGUAGES, verbose_name='Idioma', max_length=2, default='pt', )
    title = models.CharField(verbose_name='Título', help_text='Insira o título do tema', max_length=255, )
    description = models.TextField(verbose_name='Descrição', null=True, blank=True, )
    date_joined = models.DateTimeField(verbose_name='Data de cadastro', help_text='Data de cadastro', auto_now_add=True, editable=False)
    objects = ThemeInternationalizationManager()

    def __str__(self):
        return '{0}'.format(self.title)

    class Meta:
        verbose_name = 'Internacionalização'
        verbose_name_plural = verbose_name
        ordering = ('-language',)

apps/application/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from geoposition.forms import GeopositionField
from apps.protectionnetwork.models import Type, ProtectionNetwork
from apps.theme.models import Theme
from apps.uf.models import UF
from apps.user.models import Users
from sorl.thumbnail.fields import ImageField
from apps.violation.models import TypeViolation, TypeViolationInternationalization

__author__ = 'teehamaral'


class LoginUserForm(forms.Form):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Usuário',
                'required': '',
                'class': 'form-control',
            }
        ))
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Senha',
                'required': '',
                'class': 'form-control',
            }
        ))

    def clean(self):
        if not authenticate(username=self.cleaned_data.get('username', ''),
                            password=self.cleaned_data.get('password', '')):
            raise ValidationError('Usuário ou senha incorreta.')


class AddUserForm(forms.ModelForm):
    TYPES = [
        ('theme_admin', 'Administrador do tema'),
        ('theme_user', 'Usuário do tema')
    ]

    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Usado para entrar no sistema',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Nome',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Sobrenome',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'E-mail',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Senha',
                'required': '',
                'class': 'form-control'
            }
        ))
    confirm_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirmação da senha',
                'required': '',
                'class': 'form-control'
            }
        ))
    institution = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Instuição',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        )
    )
    departament = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Departamento',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    cell = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(00) 9 0000-0000',
                'autocomplete': 'off',
                'class': 'form-control celular'
            }
        ))
    phone = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(00) 9 0000-0000',
                'autocomplete': 'off',
                'class': 'form-control telefone'
            }
        ))
    type = forms.ChoiceField(
        required=False,
        choices=TYPES,
        widget=forms.RadioSelect()
    )
    is_active = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput()
    )

    class Meta:
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'is_active', 'institution',
                  'departament', 'cell', 'phone', 'type', ]
        model = Users

    def clean(self):
        list_group = ('theme_admin', 'theme_user', u'')
        if not self.cleaned_data.get(u'type') in list_group:
            raise ValidationError('Selecione um tipo válido.')

        if self.cleaned_data.get('password') != self.cleaned_data.get('confirm_password'):
            raise ValidationError('Senha e confirmação de senha não conferem')

        user_app = Users.objects.filter(username=self.cleaned_data.get(u'username'))
        if user_app.count() > 0:
            raise ValidationError('Este username já foi cadastrado anteriormente.')

        return self.cleaned_data


class EditUserForm(forms.ModelForm):
    TYPES = [
        ('theme_admin', 'Administrador do tema'),
        ('theme_user', 'Usuário do tema')
    ]

    first_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Nome',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    last_name = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Sobrenome',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': 'E-mail',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    institution = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Instuição',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        )
    )
    departament = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Departamento',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))
    cell = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(00) 9 0000-0000',
                'autocomplete': 'off',
                'class': 'form-control celular'
            }
        ))
    phone = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '(00) 9 0000-0000',
                'autocomplete': 'off',
                'class': 'form-control telefone'
            }
        ))
    type = forms.ChoiceField(
        required=False,
        choices=TYPES,
        widget=forms.RadioSelect()
    )
    is_active = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput()
    )

    class Meta:
        fields = ['first_name', 'last_name', 'email', 'is_active', 'institution',
                  'departament', 'cell', 'phone', 'type', ]
        model = Users


class ChangePasswordForm(forms.Form):
    password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Senha',
                'required': '',
                'class': 'form-control'
            }
        ))
    confirm_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Confirmação da senha',
                'required': '',
                'class': 'form-control'
            }
        ))

    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('confirm_password'):
            raise ValidationError('Senha e confirmação de senha não conferem')

        return self.cleaned_data


class ForgotPasswordForm(forms.Form):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Usuário cadastrado no sistema',
                'required': '',
                'autocomplete': 'off',
                'class': 'form-control'
            }
        ))

    def clean(self):
        user = Users.objects.filter(username=self.cleaned_data.get('username'))
        if user.count() > 0:
            user = user[0]
            if not user.email:
                raise ValidationError(
                    'O usuário informado foi encontrado, mas não há um e-mail cadastrado para enviarmos a nova senha. Por favor, entre em contato com o administrador do sistema.')
        else:
            raise ValidationError('O usuário informado não consta em nossa base de dados.')

        return self.cleaned_data


class AddTypeProctetionNetworkForm(forms.ModelForm):
    color = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'autocomplete': 'off',
                'class': "form-control color{hash:true, pickerFaceColor:'transparent', pickerFace:3, pickerBorder:0, pickerInsetColor:'black'}"
            }
        ))
    icon = ImageField(blank=True, null=True)

    class Meta:
        model = Type
        fields = ['color', 'icon']

    def clean(self):
        return self.cleaned_data


class AddTypeProctetionNetworkInternationalizationForm(forms.Form):
    name_pt = forms.CharField(
        required=True,
        label='Nome *',
        widget=forms.TextInput(

templates/application/typesviolation/edit.html
{% extends 'application/base.html' %}

{% block title %}Editar tipo de violação - Proteja Brasil{% endblock %}

{% block extracss %}
    <style>
        .tab-content {
            margin: 20px 0 0 0;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="row">
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'app_typesviolationlist' %}">
                    Tipos de violação
                </a>
            </li>
            <li class="active">Editar</li>
        </ul>
    </div>

    <div class="row">
        <div class="container col-lg-6" style="float: none;">

            <h2>
                Editar tipo de violação

                <a href="javascript:history.back();" class="back">
                    <i class="glyphicon glyphicon-chevron-left"></i> voltar
                </a>

            </h2>

            <form class="form-horizontal" action="{% url 'app_typesviolationedit' current.id %}" method="POST"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#pt" data-toggle="tab" aria-expanded="true">Português *</a></li>
                        <li class=""><a href="#en" data-toggle="tab" aria-expanded="false">English</a></li>
                        <li class=""><a href="#es" data-toggle="tab" aria-expanded="false">Español</a></li>
                    </ul>
                    <div id="myTabContent" class="tab-content">
                        <div class="tab-pane fade active in" id="pt">
                            <p class="help-block">
                                O idioma português é obrigatório.
                            </p>

                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_pt">{{ form_info.name_pt.label }}</label>
                                    {{ form_info.name_pt }}
                                    {{ form_info.name_pt.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_description_pt">{{ form_info.description_pt.label }}</label>
                                    {{ form_info.description_pt }}
                                    {{ form_info.description_pt.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_action_pt">{{ form_info.action_pt.label }}</label>
                                    {{ form_info.action_pt }}
                                    {{ form_info.action_pt.errors }}
                                    <p class="help-block">
                                        {{ form_info.action_pt.help_text }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="en">
                            <p class="help-block">
                                Fields marked with * are required.
                            </p>

                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_en">{{ form_info.name_en.label }}</label>
                                    {{ form_info.name_en }}
                                    {{ form_info.name_en.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_description_en">{{ form_info.description_en.label }}</label>
                                    {{ form_info.description_en }}
                                    {{ form_info.description_en.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_action_en">{{ form_info.action_en.label }}</label>
                                    {{ form_info.action_en }}
                                    {{ form_info.action_en.errors }}
                                    <p class="help-block">
                                        {{ form_info.action_en.help_text }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="es">
                            <p class="help-block">
                                Los campos marcados con * son obligatorios.
                            </p>
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_name_es">{{ form_info.name_es.label }}</label>
                                    {{ form_info.name_es }}
                                    {{ form_info.name_es.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_description_es">{{ form_info.description_es.label }}</label>
                                    {{ form_info.description_es }}
                                    {{ form_info.description_es.errors }}
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-lg-12">
                                    <label for="id_action_es">{{ form_info.action_es.label }}</label>
                                    {{ form_info.action_es }}
                                    {{ form_info.action_es.errors }}
                                    <p class="help-block">
                                        {{ form_info.action_es.help_text }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="id_theme">Tema *</label>
                            {{ form.theme }}
                            {{ form.theme.errors }}
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="typesprotectionnetwork">Tipos de rede de proteção *</label>
                            <select name="typesprotectionnetwork" multiple id="typesprotectionnetwork"
                                    class="form-control" required>
                                {% for tp in types_protectionnetwork %}
                                    <option {% if tp.id in current_typesprotectionnetwork_id %}selected{% endif %}
                                            value="{{ tp.id }}">{{ tp.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <label for="categories_typeviolation">Categorias</label>
                            <select name="categories_typeviolation" multiple id="categories_typeviolation"
                                    class="form-control">
                                {% for category in categories_typeviolation %}
                                    <option {% if category.0 in current_categoriesviolationtype_id %}selected{% endif %}
                                            value="{{ category.0 }}">{{ category.1 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-primary right">Salvar</button>
                        </div>
                    </div>
                </fieldset>
            </form>

        </div>
    </div>



{% endblock %}